[client]
showErrorDetails = "type"

[theme]

primaryColor = "#305273"


backgroundColor = "#292929"

secondaryBackgroundColor = "#4A4848"

textColor = "#FFF6ED"

#font = "sans-serif"


#tu poriesit farby pri slidery
#https://docs.streamlit.io/develop/concepts/configuration/theming-customize-colors-and-borders#textcolor-and-linkcolor


